testing unit test - in pipeline
ruthlennonatu/bsc23grassroots pull request #135
Opened 2023-12-07 18:02 UTC by PratikShelke-1

2023-12-08 18:53 UTC, L00163597 commented on README.md
This is fine to keep on main

2023-12-08 18:54 UTC, L00163597 commented on Source/grassroots/__pycache__/tests.cpython-310.pyc
Same again, merge or remove

2023-12-08 18:54 UTC, L00163597 commented on Source/grassroots/migrations/0001_initial.py
Unsure if this is needed

2023-12-08 18:55 UTC, L00163597 commented on Source/grassroots/migrations/__pycache__/0001_initial.cpython-310.pyc
Same as above

2023-12-08 18:58 UTC, L00163597 requested changes
Make these below changes:

- [x] Move ed2deploy file to it's own branch until secrets are added
- [ ] Merge this branch from Develop. There is a lot of files here that are already in Develop branch, making it look like you are adding new files, which you are not.

Overall, unsure if the migration files are needed. Merge from Develop is needed to keep this branch up to date. I changed this branch's base to Develop, as main should not be directly merged into from a feature branch.

2023-12-09 19:10 UTC, PratikShelke-1 commented on Source/grassroots/test_django.py
This is done. I have put it in the test folder and also i have deleted the file from main

2023-12-09 19:10 UTC, PratikShelke-1 commented on Source/grassroots/tests.py
Done

2023-12-09 19:13 UTC, PratikShelke-1 commented
> Make these below changes:
> 
> * [x]  Move ed2deploy file to it's own branch until secrets are added
> * [x]  Merge this branch from Develop. There is a lot of files here that are already in Develop branch, making it look like you are adding new files, which you are not.
> 
> Overall, unsure if the migration files are needed. Merge from Develop is needed to keep this branch up to date. I changed this branch's base to Develop, as main should not be directly merged into from a feature branch.

Above changes has been done as requested

2023-12-09 19:40 UTC, L00163597 commented on .github/workflows/ec2deploy.yml
This is only working on your fork right now, so put this in it's own branch. If you already have this in it's own branch, delete it from here

2023-12-09 19:52 UTC, L00163597 commented on Source/grassroots/__pycache__/test_django.cpython-310.pyc
Remove all __pycache__ folders and their contents

2023-12-09 19:52 UTC, L00163597 commented on Source/grassroots/__pycache__/test_django.cpython-310.pyc
Remove all pycache folders and their contents

2023-12-09 19:57 UTC, L00163597 requested changes
Make sure all pycache folders are deleted with their content from all folders

2023-12-09 20:02 UTC, PratikShelke-1 commented
Done. Please check now

2023-12-09 20:36 UTC, merged